/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of
 * [./test/virtual/cjs/demo-test-3.cjs]{@link ./test/virtual/cjs/demo-test-3.cjs}
 *
 **/
import chalk000  from "chalk-cjs";
import colorConvert  from "color-convert-cjs";
import magnimus  from "mama-magnimus";
import magnimus2  from "mama-magnimus-cjs";
import rgbhex  from "rgb-hex-cjs";
import INFO1  from "./test/virtual/cjs/dep-1.mjs";
import INFO2  from "./test/virtual/cjs/dep-2.mjs";
import INFO3  from './test/virtual/cjs/dep-3.mjs';
import INFO4  from "./test/virtual/cjs/something.mjs";
import INFO5  from "./test/virtual/cjs/something.mjs";
import path  from "path";
import {DIRECTION, MESSAGE}  from "./test/virtual/cjs/dep-1.mjs";/** const chalk001 = require("chalk-cjs"); **/

const aa = "const chalk003 = require(\"chalk-cjs\");"







const bb = `
    const chalk004 = require("chalk-cjs");
    
    const chalk005 = require("chalk-cjs");
`




class SomeClass
{
    constructor()
    {
        console.log(DIRECTION)
        console.log(MESSAGE)
        console.log(INFO1)
    }
}

export default SomeClass;