/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * [./test/virtual/cjs/demo-test-4.cjs]{@link ./test/virtual/cjs/demo-test-4.cjs}
 * 
 **/    
/**
 */
const SPECIAL_CONSTANTS = {
    WELCOME_CONTENT: "Welcome",
};

const SPECIAL_CONSTANTS_2 = {
    COMMAND_NOT_SENT               : "COMMAND_NOT_SENT",
};

export default {SPECIAL_CONSTANTS, SPECIAL_CONSTANTS_2};