name: Test
env:
  TO_ESM_APP_NAME: "release/to-esm"
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - ".vscode/**"
jobs:
  set-version:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
        uses: thimpat/to-esm/.github/actions/checkout@ci
      - name: Install dependencies
        shell: powershell
        run: npm install
      - name: Test
        shell: powershell
        run: |
          npm test
