name: Build
env:
  TO_ESM_APP_NAME: "release/to-esm"
on:
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - "**.md"
      - ".vscode/**"
jobs:
  set-version:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Check out Git repository
        uses: thimpat/to-esm/.github/actions/checkout@main
      - name: Install dependencies
        shell: powershell
        run: npm install
      - name: Upgrade version
        shell: powershell
        run: |
          npm test
          npx semantic-release
